### PR TITLE
Initial nse script for kubernetes version

### PR DESCRIPTION
**Pull request by jeremypruitt**

### CODE REVIEW

**Comment by jeremypruitt** [comment]
@jsmyth Make sure to only approve. I will squash and merge once approved.

**Comment by jsmyth** [comment]
I see a squash me commit. Did you want to squash it? :)

**Review by jsmyth — APPROVED** [review]

**Comment by jeremypruitt** [comment]
```
nmap --script=./kubernetes-version.nse localhost -sV -p 8443
Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-17 21:15 PDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000099s latency).
Other addresses for localhost (not scanned): ::1

PORT     STATE SERVICE        VERSION
8443/tcp open  ssl/kubernetes Kubernetes v1.10.0
| fingerprint-strings: 
|   FourOhFourRequest: 
|     HTTP/1.0 403 Forbidden
|     Content-Type: application/json
|     X-Content-Type-Options: nosniff
|     Date: Thu, 18 Oct 2018 04:15:50 GMT
|     Content-Length: 212
|     {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User "system:anonymous" cannot get path "/nice ports,/Trinity.txt.bak"","reason":"Forbidden","details":{},"code":403}
|   GenericLines, Help, RTSPRequest, SSLSessionReq: 
|     HTTP/1.1 400 Bad Request
|     Content-Type: text/plain; charset=utf-8
|     Connection: close
|     Request
|   GetRequest: 
|     HTTP/1.0 403 Forbidden
|     Content-Type: application/json
|     X-Content-Type-Options: nosniff
|     Date: Thu, 18 Oct 2018 04:15:50 GMT
|     Content-Length: 185
|     {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User "system:anonymous" cannot get path "/"","reason":"Forbidden","details":{},"code":403}
|   HTTPOptions: 
|     HTTP/1.0 403 Forbidden
|     Content-Type: application/json
|     X-Content-Type-Options: nosniff
|     Date: Thu, 18 Oct 2018 04:15:50 GMT
|     Content-Length: 189
|_    {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User "system:anonymous" cannot options path "/"","reason":"Forbidden","details":{},"code":403}
| kubernetes-version: 
|   buildDate: 2018-03-26T16:44:10Z
|   goVersion: go1.9.3
|   major: 1
|   minor: 10
|   compiler: gc
|   platform: linux/amd64
|   gitVersion: v1.10.0
|   gitTreeState: clean
|_  gitCommit: fc32d2f3698e36b93322a3465f63a14e9f0eaead

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 93.17 seconds
```

**Comment by jeremypruitt** [comment]
```
nmap --script=./kubernetes-version.nse localhost
Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-17 21:13 PDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000080s latency).
Other addresses for localhost (not scanned): ::1
Not shown: 998 closed ports
PORT     STATE SERVICE
8080/tcp open  http-proxy
8443/tcp open  kubernetes
| kubernetes-version: 
|   minor: 10
|   goVersion: go1.9.3
|   gitTreeState: clean
|   compiler: gc
|   gitVersion: v1.10.0
|   major: 1
|   gitCommit: fc32d2f3698e36b93322a3465f63a14e9f0eaead
|   buildDate: 2018-03-26T16:44:10Z
|_  platform: linux/amd64

Nmap done: 1 IP address (1 host up) scanned in 0.39 seconds
```

**Pull request merged**
